### ISSUE TITLE
Getting error while building with ninja

### ISSUE THREAD

**Issue by vinay-damodaran** [MeshFEM/Inflatables#1]
I'm trying to build using ninja and the build stops due to an error in `Inflatables/3rdparty/MeshFEM/3rdparty/Catch2/single_include/catch2/catch.hpp:10881`  saying size of array `altStackMem` is not an integral constant-expression
`char FatalConditionHandler::altStackMem[sigStackSize] = {};`

Is there any workaround for this issue?
Thanks!

**Comment by jpanetta** [comment]
This was an issue in Catch2 that is supposed to have been fixed in v2.13.5. I have updated this dependency, which hopefully fixes your build error. You'll either need to recursively clone a fresh copy of the `Inflatables` repository or do a `git submodule update --recursive` after pulling to get the update.

**Comment by vinay-damodaran** [comment]
It works now, thank you!
